- name: Install Python and dependencies
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present

- name: Install app dependencies from requirements.txt
  pip:
    requirements: /path/to/requirements.txt

- name: Start the Python app
  systemd:
    name: myapp
    state: started
    enabled: yes
